#!/usr/bin/env ruby

class String
  # from http://qiita.com/quattro_4/items/f9e0884f2efe7e8c033a
  #   colorization
  #     from http://stackoverflow.com/questions/1489183/colorized-ruby-output
  def red ; colorize(31) ; end
  def green ; colorize(32) ; end
  def yellow ; colorize(33) ; end
  def pink ; colorize(35) ; end
end

def commit_target_is_authorised_branch?
  current_branch = `git branch | grep "^* " | tr -d "* "`.chomp
  if current_branch == "develop" or current_branch == "master"
    puts ("Warning: can not commit on " + current_branch).red
    puts "If you want to commit forcibly, use \"git commit --no-verify\"".red
    return false
  end
  return true
end

unless commit_target_is_authorised_branch?
  exit 1
end
