#!/usr/bin/env ruby
require_relative './String+color.rb'

$current_branch = `git branch | grep "^* " | tr -d "* "`.chomp

def on_authorised_branch?
  ! ($current_branch == "develop" or $current_branch == "master")
end

unless on_authorised_branch?
  puts ("Warning: can not commit on " + $current_branch).red
  puts "If you want to commit forcibly, use \"git commit --no-verify\"".red
  exit 1
end
